CC=cl

CFLAGS=-MT -nologo -O2 -Iinclude -Iwin32\include -D__WIN32__
CFLAGS_EXE=-Fe
LDFLAGS=win32\lib\libpng.lib win32\lib\zlib.lib win32\lib\libhpdf.lib
all: code2pdf pp
code2pdf: code2pdf.c
	$(CC) $(CFLAGS_EXE)$@ $(CFLAGS) code2pdf.c $(LDFLAGS)
pp: pp.c
	$(CC) $(CFLAGS_EXE)$@ $(CFLAGS) pp.c

